sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: UfoaKPGfQmB4MbdSuw/HbnIDmHZ1LBtEhXrYPDSYhVQg9UPPpShJ6aFX84msluC55/QnwFWqKl2XJzr5t6BoUsZQtvYOfEcD1qyzCGyNQMprhwu5h183jpKsB+7dz3Qp6XtGVRiwF8UaV3Y7AeFw89/7aOPkcYrq/yXXFbD44ywIyogQCPZ7CrrxKrJ2lofL3QhurvBnlN+58Llm1UPerCDuovGQw2GPw/JJSwVgXgcQbnA3hq+wegV2gx8y/GJAvjWqwRIISIKTaUVvksV0ru9R5IeyoS6rFfnu+iB4KfaXyg62GtfCCsAwlAA0zMxEP5a2RcaHr6v2oq/1vuIyopcdUZpoeHM6jxJ0kcoelT0TvCnEYWEz19dRwz7GtTYPnixD3poLfttinAPAL+FvNPdOQEDBVUQrFwmcfy9e6YhlpQ4UiwqENfcg1fPwrYusMv4fxhbtmCfzyxTHjBy13Ha0fAy4kVcHun5NIyXm2m6kP311heqVsyZSchweZSWuKvmUWyYftroYA5TD+v1RcsmC8EqKYp4DfbvEV79xyA+9fPZVy/GVqtSleWdpQhNJ/zKw9NE2bckGrTIM+TTy3COieMm17DrH236cEZQImArq+dDj4GpLJv2OUzQvcum9zfsfLMigqDtN4TaAOBYyjNeh1KxjM0lqmIdJB8Y1RKU=
  - secure: Ik+gPlX2HLgYug8B6t/XnFcIxBLhfYfwd2UOFdxUmL123hOdMsxQ0VIxpQqL88+F2E8Z8P7cikmqNm7xtxc0fDY1fTO8VaJUEyokLdRGs3EH/3UPWtSR6dRAN1cgrnEIuhhZOvMa2gjbyZQSmWj6iAOEgte22hXa98sUggcPutaB3w3GZJe5OdhMcKLuTwazYK6dNW8xT8pqg550OJ4SC6S8jRcF5aBuBoGukcr4rOdFjZT/L6Uz5EIPHSvt998Al8o9Z6jgqxI0XzZ+kQF3R17+KU4D9GPnQCt6gY8k17Z4Zo2yfqMBy2vYvsCsfDb2T59J+VpEjk1PW4fKBoNH4/uweCKZX7ZZ7d6deR4ku/djXgNta8ZuXjhdxqYdDWjS4zwkwvb7SQvCcj1CgmkkZ7aOUcjG7G978jjvD73BbagiYaaUTM7qXL/WY+RzD7DY1PoYDoyPD3oS6F01P0N7y/6c4etEusyCNzmF4hAP2XkelorQEg8IN6cM0wG++K4PK64v0w9thq0PoiMFQjVDLtV5H/TOpK31AF0IpqbucJFY761YX8cd6KaYvyD4+3JzCXJWmNgN5CFt4QI3zpfilw8gx1TmW3kbq8LPVrzfWdZhnhYLFtuHRRongowUPtrcLk+oQp7N9VP5qT83QLSqBZRntcIEJq4iZdLaVU2Tyho=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - secure: L5h6Gvn/dKkqNwaW1Nos2FEALwfkQPaC6yT3ic5SKzkCH0ELbTiI1Nb64HB4NBxLjP7qoEfn/Mp67lZpwEqx8DdWi+pz7HYr1gLcKKmnbp9epGLlFGBQNqYoYEQWBY1TbghMLQ3NkzyW0wvRF9HP575vopwBoukFFRmUNDTst0OfEerO/dicxdFvs7u9Jpw1tYBiykuKjksW8R2jjwKos1ieDDJ+hRRPU7e4h+VIDcFAKqctxQHZB5cf05tR77QxXxd6apSZMQaeq9KNU+wdLDYQhpRmuEJU06cwJE6ibxwQe3iAmjot1sqbgVBKK5+Rt9U4jPF0baeCh21fmJUdL8RWnVjPKxbJs2MT72ZD+A4m8cZ6s/SZBVmdef9+l57nJgmtEOmDWQfmr8nwBe/Vf/nc2NrYhiMKWE5j4785QRyKBbWfFxbl/Mb8yHwRpbYYsYk4PWETVl1u9xWDKL0YPtF30c7DTbaVCmrdZXmMX7hBMD/j74vlTZy+794eaJsgo4uGs8+HsOA3HiDgc1FV3fAc/vnjkvCxUzgm3C207m/UjeyUUX+iPNGAKfr3wC8iSnOto/J4K99b94I/UAj7vyeJM+04fDaJq3vT1DxLC8+2sMW/5HctZQL6k14DqvmSBGbh9YxmSGwm+1nc0IOXSEB+Y/KOwn4gvK64hjL1S40=
