name: Package and release
on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Trim changelog
        run: sed -ni '1p;2,/^###/{/^###/q;p;}' CHANGELOG.md

      - name: Package and release
        uses: BigWigsMods/packager@v1.0.2

      - name: Package and release for Classic
        uses: BigWigsMods/packager@v1.0.2
        with:
          args: -g classic

      - name: Package and release for BCC
        uses: BigWigsMods/packager@v1.0.2
        with:
          args: -g bcc
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
